apiVersion: v1
kind: Service
metadata:
  name: resume-service-lb
  namespace: ${NAMESPACE}              
  labels:
    app: resume-service
    environment: ${ENVIRONMENT}        
spec:
  type: LoadBalancer
  selector:
    app: resume-service
  ports:
  - port: 8080
    targetPort: 8080